channels:
  - conda-forge
  - defaults

dependencies:
  - coveralls
  - cython
  - jsonschema
  - make
  - matplotlib
  - meson
  - moorpy
  - ninja
  - nlopt
  - numpy>=1.26
  - numpydoc
  - openmdao>=3.31
  - openpyxl
  - pandas
  - pip
  - pydoe3
  - pyoptsparse<1.3
  - pytest
  - pytest-cov
  - python-benedict
  - pyyaml
  - ruamel.yaml
  - scipy
  - setuptools
  - simpy
  - sortedcontainers
  - statsmodels
  - swig
  - pip:
    - marmot-agents
    - dearpygui
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py (only needed if local system has mpi built and is used)
